/**
 * 第一階層：抽象定義（Global / Primitive Tokens）
 */

// システム・モジュール名に関する定数群
export const WORDS_SYSTEM = {
  SYSTEM_ID: 'p2608',
  SYSTEM_NAME: '統合管理システム',
  SYSTEM_NAME_INVENTORY: '在庫管理システム',
  SYSTEM_NAME_PROJECT: '工賃管理システム',

  // モジュール名
  AGGREGATION: '集計系',
  RECORDING: '記録系',
  SETTINGS: '設定系',
  REPORT: '参照有・入力無',
  TRANSACTION_KANA: '参照有・入力有',
  SUB_MASTER: '参照無・入力有',

  // メニュー・画面名
  INVENTORY: '在庫集計',
  TRANSACTION: '受入・払出記録',
  STOCKTAKING: '棚卸記録',
  MASTER: '品目情報',
  CATEGORY_SETTING: 'カテゴリ設定',
  LOCATION_SETTING: '保管場所設定',
  SUPPLIER_SETTING: '仕入先設定',
  STAFF_SETTING: '職員設定',
  PROJECT_INFO: '案件情報',
  PROJECT_USER: '利用者設定',
  CLIENT_SETTING: '取引先設定',
  SKILL_SETTING: 'スキル設定',
  BASE_WAGE_SETTING: '工賃単価設定',
  DAILY_WORK_RECORD: '作業記録',
  PROGRESS_RECORD: '進捗記録',
  FINANCIAL_RECORD: '収支記録',
  PROJECT_SUMMARY: '案件状況集計',
  ASSIGNEE_SUMMARY: '担当状況集計',
  BUDGET_PLANNING: '予算編成',
  ASSIGNEE_ALLOCATION: '担当者割当',
};

// 汎用・共通の定数群
export const WORDS_COMMON = {
  CATEGORY: 'カテゴリ',
  TYPE: '区分',
  QUANTITY: '数量',
  DIFFERENCE: '差異',
  RESTRICTION: '制限',
  DESCRIPTION: '説明',
  ADD: '追加',
  EDIT: '編集',
  DELETE: '削除',
  SAVE: '確定',
  CANCEL: '取消',
  CLOSE: '閉じる',
  YOMIGANA: 'よみがな',
  UNIT: '単位',
  YES: 'はい',
  YES_VALUE: 'yes',
  NO: 'いいえ',
  NO_VALUE: 'no',
};

// 人に関する定数群
export const WORDS_PERSON = {
  NAME: '氏名',
  ROLE: 'ロール',
  PERSON_IN_CHARGE: '記録者',
  ASSIGNEE: '担当者',
  ASSIGNEE_TYPE: '担当者区分',
  ROLE_ADMIN: 'システム管理者',
  ROLE_STAFF: '職員',
  ROLE_MEMBER: '利用者',
};

// 連絡先・認証に関する定数群
export const WORDS_CONTACT_AUTH = {
  EMAIL: 'メールアドレス',
  EMAIL_PLACEHOLDER: 'user@example.com',
  PASSWORD: 'パスワード',
  PASSWORD_PLACEHOLDER: '••••••••',
  PHONE: '電話番号',
  LOGIN_INVENTORY: '在庫管理システムへログイン',
  LOGIN_PROJECT: '工賃管理システムへログイン',
  LOGOUT: 'ログアウト',
};

// 組織・場所に関する定数群
export const WORDS_ORG_LOCATION = {
  SUPPLIER: '仕入先',
  CLIENT: '取引先',
  CUSTOMER: '顧客',
  OUTSOURCE: '外注先',
  LOCATION: '保管場所',
  STANDARD_LOCATION: '標準保管場所',
  CLIENT_INTERNAL_BUSINESS: '無し（自主事業）',
};

// 時間・記録に関する定数群
export const WORDS_TIME = {
  START_DATE: '開始日',
  END_DATE: '終了日',
  WORK_TIME: '作業時間 (h)',
  CURRENT_MONTH_WORK_TIME: '今月作業時間 (h)',
};

// 在庫・品目に関する定数群
export const WORDS_INVENTORY = {
  ITEM: '品目',
  STANDARD_PRICE: '標準単価',
  STANDARD_PURCHASE_QTY: '標準仕入数量',
  BOOK_INVENTORY: '帳簿在庫',
  ACTUAL_INVENTORY: '実在庫',
  TRANSACTION_IN: '受入',
  TRANSACTION_OUT: '払出',
};

// 案件・作業に関する定数群
export const WORDS_PROJECT = {
  PROJECT: '案件',
  PROJECT_TYPE: '案件区分',
  PROJECT_TYPE_ONE_OFF: '単発',
  PROJECT_TYPE_ONE_OFF_VALUE: 'one-off',
  PROJECT_TYPE_ONGOING: '継続',
  PROJECT_TYPE_ONGOING_VALUE: 'ongoing',
  TASK: 'タスク',
  SKILL: 'スキル',
  REQUIRED_SKILLS: 'スキル',
  INCENTIVE_BUDGET: 'インセンティブ予算額',
  CONTRIBUTION_RATIO: '報酬配分比',
  PROGRESS_RATE: '進捗率',
  STATUS_NOT_STARTED: '未着手',
  STATUS_IN_PROGRESS: '進行中',
  STATUS_COMPLETED: '完了',
  STATUS_CANCELED: '中止',
  PREV_MONTH_PROGRESS: '月初進捗率 (%)',
  CURRENT_MONTH_PROGRESS: '月末進捗率 (%)',
  REVENUE: '収益',
  EXPENSE: '費用',
  RESERVE: '積立金',
  SURPLUS: '余剰',
  SUBJECT: '科目',
  AMOUNT: '金額',
  TOTAL: '合計',
  SUBJECT_REVENUE_SALES: '売上',
  SUBJECT_REVENUE_OTHER: 'その他収益',
  SUBJECT_EXPENSE_LABOR: '労務費・外注加工費',
  SUBJECT_EXPENSE_OTHER: 'その他費用',
  BASE_WAGE: '工賃単価',
  SUBJECT_RESERVE_WAGE: '工賃変動積立金',
  SUBJECT_RESERVE_EQUIPMENT: '設備等修繕維持積立金',
  SUBJECT_SURPLUS: '余剰',
};

// メッセージに関する定数群
export const WORDS_MESSAGE = {
  SAVE_SUCCESS: '保存が完了しました。',
  SAVE_ERROR: '保存中にエラーが発生しました。コンソールをご確認ください。',
  EMPTY_INVENTORY: '在庫データがありません',
  EMPTY_TRANSACTION: '記録データがありません',
  EMPTY_STOCKTAKING: '棚卸データがありません',
  EMPTY_MASTER: 'マスタデータがありません',
  EMPTY_CATEGORY: 'カテゴリデータがありません',
  EMPTY_LOCATION: '保管場所データがありません',
  EMPTY_SUPPLIER: '仕入先データがありません',
  EMPTY_STAFF: '職員データがありません',
  EMPTY_PROJECT_USER: '利用者データがありません',
  EMPTY_CLIENT: '取引先データがありません',
  EMPTY_SKILL: 'スキルデータがありません',
  EMPTY_BASE_WAGE: '工賃単価データがありません',
  EMPTY_FINANCIAL_RECORD: '収支記録がありません',
  EMPTY_DAILY_WORK_RECORD: '作業記録がありません',
  EMPTY_PROGRESS_RECORD: '進捗記録がありません',
  EMPTY_BUDGET: '予算データがありません',
  RESTRICTED_EDIT: '最新棚卸以前のデータは編集不可です',
  PAGE_UNDER_CONSTRUCTION: '選択されたページは現在開発中です。',
  FEATURE_NOT_IMPLEMENTED: '編集機能は未実装です',
  FETCH_ERROR: 'データの取得に失敗しました',
  LOADING: 'Loading...',
  SELECT: '選択してください',
};

/**
 * 第二階層：具象定義（Semantic / Component Tokens）
 */

export const SYSTEM_NAME = WORDS_SYSTEM.SYSTEM_NAME;
export const SYSTEM_NAME_INVENTORY = WORDS_SYSTEM.SYSTEM_NAME_INVENTORY;
export const SYSTEM_NAME_PROJECT = WORDS_SYSTEM.SYSTEM_NAME_PROJECT;
export const SYSTEM_ID = WORDS_SYSTEM.SYSTEM_ID;

export const MENU_CATEGORIES = {
  AGGREGATION: WORDS_SYSTEM.AGGREGATION,
  RECORDING: WORDS_SYSTEM.RECORDING,
  SETTINGS: WORDS_SYSTEM.SETTINGS,
};

export const MENU_SUBCATEGORIES = {
  AGGREGATION: WORDS_SYSTEM.REPORT,
  RECORDING: WORDS_SYSTEM.TRANSACTION_KANA,
  SETTINGS: WORDS_SYSTEM.SUB_MASTER,
};

export const PAGE_NAMES = {
  INVENTORY: WORDS_SYSTEM.INVENTORY,
  TRANSACTION: WORDS_SYSTEM.TRANSACTION,
  STOCKTAKING: WORDS_SYSTEM.STOCKTAKING,
  MASTER: WORDS_SYSTEM.MASTER,
  CATEGORY: WORDS_SYSTEM.CATEGORY_SETTING,
  LOCATION: WORDS_SYSTEM.LOCATION_SETTING,
  SUPPLIER: WORDS_SYSTEM.SUPPLIER_SETTING,
  STAFF: WORDS_SYSTEM.STAFF_SETTING,
  PROJECT_INFO: WORDS_SYSTEM.PROJECT_INFO,
  PROJECT_USER: WORDS_SYSTEM.PROJECT_USER,
  CLIENT: WORDS_SYSTEM.CLIENT_SETTING,
  SKILL: WORDS_SYSTEM.SKILL_SETTING,
  SKILL_LEVEL: 'スキルレベル設定',
  SKILL_EVALUATION: 'スキル評価',
  BASE_WAGE: '工賃単価設定',
  BASE_WAGE_ASSIGNMENT: '工賃単価割当',
  DAILY_WORK_RECORD: WORDS_SYSTEM.DAILY_WORK_RECORD,
  PROGRESS_RECORD: '進捗状況',
  FINANCIAL_RECORD: WORDS_SYSTEM.FINANCIAL_RECORD,
  REWARD_ALLOCATION: '報酬配分',
  PROJECT_SUMMARY: WORDS_SYSTEM.PROJECT_SUMMARY,
  ASSIGNEE_SUMMARY: WORDS_SYSTEM.ASSIGNEE_SUMMARY,
  BUDGET_PLANNING: WORDS_SYSTEM.BUDGET_PLANNING,
  ASSIGNEE_ALLOCATION: WORDS_SYSTEM.ASSIGNEE_ALLOCATION,
  WAGE_SUMMARY: '工賃・控除集計',
};

export const TABLE_COLUMNS = {
  // 共通
  YOMIGANA: WORDS_COMMON.YOMIGANA,
  DESCRIPTION: WORDS_COMMON.DESCRIPTION,
  NAME: WORDS_PERSON.NAME,
  CATEGORY: WORDS_COMMON.CATEGORY,
  ITEM: WORDS_INVENTORY.ITEM,
  PERSON_IN_CHARGE: WORDS_PERSON.PERSON_IN_CHARGE,

  // 保管場所・カテゴリ・取引先
  LOCATION_NAME: WORDS_ORG_LOCATION.LOCATION, // 統合
  CATEGORY_NAME: WORDS_COMMON.CATEGORY, // 統合
  SUPPLIER_NAME: WORDS_ORG_LOCATION.SUPPLIER, // 統合
  CLIENT_NAME: WORDS_ORG_LOCATION.CLIENT, // 統合

  // アカウント
  ROLE: WORDS_PERSON.ROLE,
  EMAIL: WORDS_CONTACT_AUTH.EMAIL,
  PASSWORD: WORDS_CONTACT_AUTH.PASSWORD,
  CONTACT_PERSON: WORDS_PERSON.ASSIGNEE, // 担当者に統合
  PHONE: WORDS_CONTACT_AUTH.PHONE,

  // 品目
  STANDARD_LOCATION: WORDS_ORG_LOCATION.STANDARD_LOCATION,
  SUPPLIER: WORDS_ORG_LOCATION.SUPPLIER,
  STANDARD_PRICE: WORDS_INVENTORY.STANDARD_PRICE,
  STANDARD_PURCHASE_QTY: WORDS_INVENTORY.STANDARD_PURCHASE_QTY,

  // 在庫・記録・棚卸
  BOOK_INVENTORY: WORDS_INVENTORY.BOOK_INVENTORY,
  ACTUAL_INVENTORY: WORDS_INVENTORY.ACTUAL_INVENTORY,
  DIFFERENCE: WORDS_COMMON.DIFFERENCE,
  LOCATION: WORDS_ORG_LOCATION.LOCATION,
  TYPE: WORDS_COMMON.TYPE,
  QUANTITY: WORDS_COMMON.QUANTITY,
  RESTRICTION: WORDS_COMMON.RESTRICTION,

  // 案件情報
  PROJECT_NAME: WORDS_PROJECT.PROJECT, // 案件に統合
  PROJECT_TYPE: WORDS_PROJECT.PROJECT_TYPE,
  START_DATE: WORDS_TIME.START_DATE,
  END_DATE: WORDS_TIME.END_DATE,
  CUSTOMER: WORDS_ORG_LOCATION.CUSTOMER,
  TASK: WORDS_PROJECT.TASK,
  REQUIRED_SKILLS: WORDS_PROJECT.REQUIRED_SKILLS,
  INCENTIVE_BUDGET: WORDS_PROJECT.INCENTIVE_BUDGET,
  ASSIGNEE: WORDS_PERSON.ASSIGNEE,
  SKILL_NAME: WORDS_PROJECT.SKILL, // スキルに統合
  SKILL_LEVEL: 'スキルレベル',
  BASE_WAGE: WORDS_PROJECT.BASE_WAGE,

  // 日次作業記録
  USER_NAME: WORDS_PERSON.ASSIGNEE, // 担当者に統合
  WORK_TIME: WORDS_TIME.WORK_TIME,
  NOTES: WORDS_COMMON.DESCRIPTION,

  // 進捗記録
  PREV_MONTH_PROGRESS: WORDS_PROJECT.PREV_MONTH_PROGRESS,
  CURRENT_MONTH_PROGRESS: WORDS_PROJECT.CURRENT_MONTH_PROGRESS,
  CURRENT_MONTH_WORK_TIME: WORDS_TIME.CURRENT_MONTH_WORK_TIME,
  CONTRIBUTION_RATIO: WORDS_PROJECT.CONTRIBUTION_RATIO,
  REWARD_ALLOCATION_AMOUNT: '報酬配分額',
  DEDUCTION_AMOUNT: '差引額',
  REWARD_UNIT_PRICE: '報酬単価',
  PROGRESS_RATE: WORDS_PROJECT.PROGRESS_RATE,
  PROJECT_STATUS: '進捗状態',
  IS_CANCELED: '中止',
  ASSIGNEE_TYPE: WORDS_PERSON.ASSIGNEE_TYPE,

  // 予算・収支
  REVENUE: WORDS_PROJECT.REVENUE,
  EXPENSE: WORDS_PROJECT.EXPENSE,
  RESERVE: WORDS_PROJECT.RESERVE,
  SURPLUS: WORDS_PROJECT.SURPLUS,
  SUBJECT: WORDS_PROJECT.SUBJECT,
  AMOUNT: WORDS_PROJECT.AMOUNT,
  TOTAL: WORDS_PROJECT.TOTAL,
  PERIOD: '時期',
  RECORDED_DATE: '記録日',
};

export const LOGIN_LABELS = {
  EMAIL: WORDS_CONTACT_AUTH.EMAIL,
  PASSWORD: WORDS_CONTACT_AUTH.PASSWORD,
};

export const BUTTON_LABELS = {
  LOGIN_INVENTORY: WORDS_CONTACT_AUTH.LOGIN_INVENTORY,
  LOGIN_PROJECT: WORDS_CONTACT_AUTH.LOGIN_PROJECT,
  LOGOUT: WORDS_CONTACT_AUTH.LOGOUT,
  ADD: WORDS_COMMON.ADD,
  SAVE: WORDS_COMMON.SAVE,
  CANCEL: WORDS_COMMON.CANCEL,
  DELETE: WORDS_COMMON.DELETE,
};

export const MESSAGES = {
  SAVE_SUCCESS: WORDS_MESSAGE.SAVE_SUCCESS,
  SAVE_ERROR: WORDS_MESSAGE.SAVE_ERROR,
  EMPTY_INVENTORY: WORDS_MESSAGE.EMPTY_INVENTORY,
  EMPTY_TRANSACTION: WORDS_MESSAGE.EMPTY_TRANSACTION,
  EMPTY_STOCKTAKING: WORDS_MESSAGE.EMPTY_STOCKTAKING,
  EMPTY_MASTER: WORDS_MESSAGE.EMPTY_MASTER,
  EMPTY_CATEGORY: WORDS_MESSAGE.EMPTY_CATEGORY,
  EMPTY_LOCATION: WORDS_MESSAGE.EMPTY_LOCATION,
  EMPTY_SUPPLIER: WORDS_MESSAGE.EMPTY_SUPPLIER,
  EMPTY_STAFF: WORDS_MESSAGE.EMPTY_STAFF,
  EMPTY_PROJECT_USER: WORDS_MESSAGE.EMPTY_PROJECT_USER,
  EMPTY_CLIENT: WORDS_MESSAGE.EMPTY_CLIENT,
  EMPTY_SKILL: WORDS_MESSAGE.EMPTY_SKILL,
  EMPTY_BASE_WAGE: WORDS_MESSAGE.EMPTY_BASE_WAGE,
  EMPTY_BASE_WAGE_ASSIGNMENT: '工賃単価割当データがありません',
  EMPTY_FINANCIAL_RECORD: WORDS_MESSAGE.EMPTY_FINANCIAL_RECORD,
  EMPTY_DAILY_WORK_RECORD: WORDS_MESSAGE.EMPTY_DAILY_WORK_RECORD,
  EMPTY_PROGRESS_RECORD: WORDS_MESSAGE.EMPTY_PROGRESS_RECORD,
  EMPTY_BUDGET: WORDS_MESSAGE.EMPTY_BUDGET,
  RESTRICTED_EDIT: WORDS_MESSAGE.RESTRICTED_EDIT,
  PAGE_UNDER_CONSTRUCTION: WORDS_MESSAGE.PAGE_UNDER_CONSTRUCTION,
  FEATURE_NOT_IMPLEMENTED: WORDS_MESSAGE.FEATURE_NOT_IMPLEMENTED,
  FETCH_ERROR: WORDS_MESSAGE.FETCH_ERROR,
  LOADING: WORDS_MESSAGE.LOADING,
};

export const PLACEHOLDERS = {
  EMAIL: WORDS_CONTACT_AUTH.EMAIL_PLACEHOLDER,
  PASSWORD: WORDS_CONTACT_AUTH.PASSWORD_PLACEHOLDER,
  SELECT: WORDS_MESSAGE.SELECT,
};

export const TRANSACTION_TYPE_OPTIONS = [
  { label: '', value: '' },
  { label: WORDS_INVENTORY.TRANSACTION_IN, value: WORDS_INVENTORY.TRANSACTION_IN },
  { label: WORDS_INVENTORY.TRANSACTION_OUT, value: WORDS_INVENTORY.TRANSACTION_OUT }
];

export const OPTIONS = {
  PROJECT_TYPE_OPTIONS: [
    { label: WORDS_PROJECT.PROJECT_TYPE_ONE_OFF, value: WORDS_PROJECT.PROJECT_TYPE_ONE_OFF_VALUE },
    { label: WORDS_PROJECT.PROJECT_TYPE_ONGOING, value: WORDS_PROJECT.PROJECT_TYPE_ONGOING_VALUE }
  ],
  YES_NO: [
    { label: WORDS_COMMON.YES, value: WORDS_COMMON.YES_VALUE },
    { label: WORDS_COMMON.NO, value: WORDS_COMMON.NO_VALUE }
  ]
};

export const STAFF_ROLE_OPTIONS = [
  { label: WORDS_PERSON.ROLE_ADMIN, value: WORDS_PERSON.ROLE_ADMIN },
  { label: WORDS_PERSON.ROLE_STAFF, value: WORDS_PERSON.ROLE_STAFF }
];

export const MEMBER_ROLE_OPTIONS = [
  { label: WORDS_PERSON.ROLE_MEMBER, value: WORDS_PERSON.ROLE_MEMBER }
];
