/**
 * 第一階層：抽象定義（Global / Primitive Tokens）
 * ドメインや概念ごとに語彙（単語・フレーズ）を抽象化して定義します。
 */

// 人・アカウントに関する定数群
export const WORDS_PERSON = {
  NAME: '氏名',
  YOMIGANA: 'よみがな',
  EMAIL: 'メールアドレス',
  EMAIL_PLACEHOLDER: 'user@example.com',
  PASSWORD: 'パスワード',
  PASSWORD_PLACEHOLDER: '••••••••',
  ROLE: '権限ロール',
  ASSIGNEE: '担当者',
  PERSON_IN_CHARGE: '記録者',
  CUSTOMER: '顧客',
  PHONE: '電話番号',
  ASSIGNEE_TYPE: '要員区分',
};

// 組織・場所に関する定数群
export const WORDS_ORG_LOCATION = {
  SUPPLIER: '仕入先',
  SUPPLIER_NAME: '仕入先名',
  CLIENT_NAME: '取引先名',
  LOCATION: '保管場所',
  LOCATION_NAME: '保管場所名',
  STANDARD_LOCATION: '標準保管場所',
};

// 時間・記録に関する定数群
export const WORDS_TIME = {
  DATE: '記録日時',
  START_DATE: '開始日',
  END_DATE: '終了日',
  WORK_TIME: '作業時間',
  CURRENT_MONTH_WORK_TIME: '今月作業時間',
};

// 在庫・品目に関する定数群
export const WORDS_INVENTORY = {
  ITEM: '品目',
  CATEGORY: 'カテゴリ',
  CATEGORY_NAME: 'カテゴリ名',
  STANDARD_PRICE: '標準単価 (円)',
  STANDARD_PURCHASE_QTY: '標準仕入数量',
  BOOK_INVENTORY: '帳簿在庫',
  ACTUAL_INVENTORY: '実在庫',
  DIFFERENCE: '差異',
  TYPE: '区分',
  QUANTITY: '数量',
  RESTRICTION: '制限',
};

// 案件・作業に関する定数群
export const WORDS_PROJECT = {
  PROJECT_ID: '案件ID',
  PROJECT_NAME: '案件名',
  TASK: 'タスク',
  REQUIRED_SKILLS: '必要スキル',
  SKILL_NAME: 'スキル名',
  WORK_CONTENT: '作業内容',
  NOTES: '備考',
  PREV_MONTH_PROGRESS: '月初進捗率 (%)',
  CURRENT_MONTH_PROGRESS: '月末進捗率 (%)',
  CONTRIBUTION_RATIO: '貢献比率',
  PROGRESS_RATE: '進捗率 (%)',
};

// アクション・UIに関する定数群
export const WORDS_UI = {
  LOGIN: 'ログイン',
  LOGIN_INVENTORY: '在庫管理システムへログイン',
  LOGIN_PROJECT: '案件管理システムへログイン',
  LOGOUT: 'ログアウト',
  ADD: '追加',
  SAVE: '確定',
  CANCEL: '取消',
  DELETE: '削除',
  EDIT: '編集',
  CLOSE: '閉じる',
  DESCRIPTION: '説明',
  SELECT: '選択してください',
};

// システム・モジュール名に関する定数群
export const WORDS_SYSTEM = {
  SYSTEM_NAME: '統合管理システム',
  SYSTEM_NAME_INVENTORY: '在庫管理システム',
  SYSTEM_NAME_PROJECT: '案件管理システム',
  SYSTEM_ID: 'p2608',
  
  // モジュール名
  INVENTORY: '在庫集計',
  TRANSACTION: '受入・払出記録',
  STOCKTAKING: '棚卸記録',
  MASTER: '品目情報',
  CATEGORY_SETTING: 'カテゴリ設定',
  LOCATION_SETTING: '保管場所設定',
  SUPPLIER_SETTING: '仕入先設定',
  STAFF_SETTING: '職員設定',
  PROJECT_INFO: '案件情報',
  PROJECT_USER: '利用者設定',
  CLIENT_SETTING: '取引先設定',
  SKILL_SETTING: 'スキル設定',
  DAILY_WORK_RECORD: '作業記録',
  PROGRESS_RECORD: '進捗記録',
  PROJECT_SUMMARY: '案件集計',

  // メニュー名
  AGGREGATION: '集計系',
  RECORDING: '記録系',
  INFORMATION: '情報系',
  SETTINGS: '設定系',
  REPORT: 'レポート',
  TRANSACTION_KANA: 'トランザクション',
  MAIN_MASTER: 'メインマスタ',
  SUB_MASTER: 'サブマスタ',
};

// メッセージに関する定数群
export const WORDS_MESSAGE = {
  SAVE_SUCCESS: '保存が完了しました。',
  SAVE_ERROR: '保存中にエラーが発生しました。コンソールをご確認ください。',
  EMPTY_INVENTORY: '在庫データがありません',
  EMPTY_TRANSACTION: '記録データがありません',
  EMPTY_STOCKTAKING: '棚卸データがありません',
  EMPTY_MASTER: 'マスタデータがありません',
  EMPTY_CATEGORY: 'カテゴリデータがありません',
  EMPTY_LOCATION: '保管場所データがありません',
  EMPTY_SUPPLIER: '仕入先データがありません',
  EMPTY_STAFF: '職員データがありません',
  EMPTY_PROJECT_USER: '利用者データがありません',
  EMPTY_CLIENT: '取引先データがありません',
  EMPTY_SKILL: 'スキルデータがありません',
  EMPTY_DAILY_WORK_RECORD: '作業記録がありません',
  EMPTY_PROGRESS_RECORD: '進捗記録がありません',
  DELETE_CONFIRM: '本当に削除しますか？',
  RESTRICTED_EDIT: '最新棚卸以前のデータは編集不可です',
  PAGE_UNDER_CONSTRUCTION: '選択されたページは現在開発中です。',
  LOGOUT_CONFIRM_PROJECT: '案件管理システムからログアウト',
  LOGOUT_CONFIRM_INVENTORY: '在庫管理システムからログアウト',
  SUCCESS_TITLE: '成功',
  ERROR_TITLE: 'エラー',
  EMPTY_DATA: 'データがありません',
  NO_OPTIONS: '選択肢がありません',
  FEATURE_NOT_IMPLEMENTED: '編集機能は未実装です',
  STAFF_SHORTAGE: '要員追加: ',
  STAFF_SURPLUS: '余剰あり: ',
  STAFF_OPTIMAL: '適正配置',
  DUMMY_LOGIC_NOTICE: '※ダミーの集計ロジックです',
  FETCH_ERROR: 'データの取得に失敗しました',
  LOADING: 'Loading...',
};

/**
 * 第二階層：具象定義（Semantic / Component Tokens）
 * コンテキスト（どこで使われるか）に基づいた別名を定義します。
 */

export const SYSTEM_NAME = WORDS_SYSTEM.SYSTEM_NAME;
export const SYSTEM_NAME_INVENTORY = WORDS_SYSTEM.SYSTEM_NAME_INVENTORY;
export const SYSTEM_NAME_PROJECT = WORDS_SYSTEM.SYSTEM_NAME_PROJECT;
export const SYSTEM_ID = WORDS_SYSTEM.SYSTEM_ID;

export const MENU_CATEGORIES = {
  AGGREGATION: WORDS_SYSTEM.AGGREGATION,
  RECORDING: WORDS_SYSTEM.RECORDING,
  INFORMATION: WORDS_SYSTEM.INFORMATION,
  SETTINGS: WORDS_SYSTEM.SETTINGS,
};

export const MENU_SUBCATEGORIES = {
  AGGREGATION: WORDS_SYSTEM.REPORT,
  RECORDING: WORDS_SYSTEM.TRANSACTION_KANA,
  INFORMATION: WORDS_SYSTEM.MAIN_MASTER,
  SETTINGS: WORDS_SYSTEM.SUB_MASTER,
};

export const PAGE_NAMES = {
  INVENTORY: WORDS_SYSTEM.INVENTORY,
  TRANSACTION: WORDS_SYSTEM.TRANSACTION,
  STOCKTAKING: WORDS_SYSTEM.STOCKTAKING,
  MASTER: WORDS_SYSTEM.MASTER,
  CATEGORY: WORDS_SYSTEM.CATEGORY_SETTING,
  LOCATION: WORDS_SYSTEM.LOCATION_SETTING,
  SUPPLIER: WORDS_SYSTEM.SUPPLIER_SETTING,
  STAFF: WORDS_SYSTEM.STAFF_SETTING,
  PROJECT_INFO: WORDS_SYSTEM.PROJECT_INFO,
  PROJECT_USER: WORDS_SYSTEM.PROJECT_USER,
  CLIENT: WORDS_SYSTEM.CLIENT_SETTING,
  SKILL: WORDS_SYSTEM.SKILL_SETTING,
  DAILY_WORK_RECORD: WORDS_SYSTEM.DAILY_WORK_RECORD,
  PROGRESS_RECORD: WORDS_SYSTEM.PROGRESS_RECORD,
  PROJECT_SUMMARY: WORDS_SYSTEM.PROJECT_SUMMARY,
};

export const TABLE_COLUMNS = {
  YOMIGANA: WORDS_PERSON.YOMIGANA,
  DESCRIPTION: WORDS_UI.DESCRIPTION,
  NAME: WORDS_PERSON.NAME,
  CATEGORY: WORDS_INVENTORY.CATEGORY,
  ITEM: WORDS_INVENTORY.ITEM,
  PERSON_IN_CHARGE: WORDS_PERSON.PERSON_IN_CHARGE,
  DATE: WORDS_TIME.DATE,
  LOCATION_NAME: WORDS_ORG_LOCATION.LOCATION_NAME,
  CATEGORY_NAME: WORDS_INVENTORY.CATEGORY_NAME,
  ROLE: WORDS_PERSON.ROLE,
  EMAIL: WORDS_PERSON.EMAIL,
  PASSWORD: WORDS_PERSON.PASSWORD,
  SUPPLIER_NAME: WORDS_ORG_LOCATION.SUPPLIER_NAME,
  CLIENT_NAME: WORDS_ORG_LOCATION.CLIENT_NAME,
  CONTACT_PERSON: WORDS_PERSON.ASSIGNEE,
  PHONE: WORDS_PERSON.PHONE,
  STANDARD_LOCATION: WORDS_ORG_LOCATION.STANDARD_LOCATION,
  SUPPLIER: WORDS_ORG_LOCATION.SUPPLIER,
  STANDARD_PRICE: WORDS_INVENTORY.STANDARD_PRICE,
  STANDARD_PURCHASE_QTY: WORDS_INVENTORY.STANDARD_PURCHASE_QTY,
  BOOK_INVENTORY: WORDS_INVENTORY.BOOK_INVENTORY,
  ACTUAL_INVENTORY: WORDS_INVENTORY.ACTUAL_INVENTORY,
  DIFFERENCE: WORDS_INVENTORY.DIFFERENCE,
  LOCATION: WORDS_ORG_LOCATION.LOCATION,
  TYPE: WORDS_INVENTORY.TYPE,
  QUANTITY: WORDS_INVENTORY.QUANTITY,
  RESTRICTION: WORDS_INVENTORY.RESTRICTION,
  PROJECT_ID: WORDS_PROJECT.PROJECT_ID,
  PROJECT_NAME: WORDS_PROJECT.PROJECT_NAME,
  START_DATE: WORDS_TIME.START_DATE,
  END_DATE: WORDS_TIME.END_DATE,
  CUSTOMER: WORDS_PERSON.CUSTOMER,
  TASK: WORDS_PROJECT.TASK,
  REQUIRED_SKILLS: WORDS_PROJECT.REQUIRED_SKILLS,
  ASSIGNEE: WORDS_PERSON.ASSIGNEE,
  SKILL_NAME: WORDS_PROJECT.SKILL_NAME,
  USER_NAME: WORDS_PERSON.ASSIGNEE,
  WORK_CONTENT: WORDS_PROJECT.WORK_CONTENT,
  WORK_TIME: WORDS_TIME.WORK_TIME,
  NOTES: WORDS_PROJECT.NOTES,
  PREV_MONTH_PROGRESS: WORDS_PROJECT.PREV_MONTH_PROGRESS,
  CURRENT_MONTH_PROGRESS: WORDS_PROJECT.CURRENT_MONTH_PROGRESS,
  CURRENT_MONTH_WORK_TIME: WORDS_TIME.CURRENT_MONTH_WORK_TIME,
  CONTRIBUTION_RATIO: WORDS_PROJECT.CONTRIBUTION_RATIO,
  PROGRESS_RATE: WORDS_PROJECT.PROGRESS_RATE,
  ASSIGNEE_TYPE: WORDS_PERSON.ASSIGNEE_TYPE,
};

export const LOGIN_LABELS = {
  EMAIL: WORDS_PERSON.EMAIL,
  PASSWORD: WORDS_PERSON.PASSWORD,
};

export const BUTTON_LABELS = {
  LOGIN: WORDS_UI.LOGIN,
  LOGIN_INVENTORY: WORDS_UI.LOGIN_INVENTORY,
  LOGIN_PROJECT: WORDS_UI.LOGIN_PROJECT,
  LOGOUT: WORDS_UI.LOGOUT,
  ADD: WORDS_UI.ADD,
  SAVE: WORDS_UI.SAVE,
  CANCEL: WORDS_UI.CANCEL,
  DELETE: WORDS_UI.DELETE,
  EDIT: WORDS_UI.EDIT,
  CLOSE: WORDS_UI.CLOSE,
};

export const MESSAGES = {
  SAVE_SUCCESS: WORDS_MESSAGE.SAVE_SUCCESS,
  SAVE_ERROR: WORDS_MESSAGE.SAVE_ERROR,
  EMPTY_INVENTORY: WORDS_MESSAGE.EMPTY_INVENTORY,
  EMPTY_TRANSACTION: WORDS_MESSAGE.EMPTY_TRANSACTION,
  EMPTY_STOCKTAKING: WORDS_MESSAGE.EMPTY_STOCKTAKING,
  EMPTY_MASTER: WORDS_MESSAGE.EMPTY_MASTER,
  EMPTY_CATEGORY: WORDS_MESSAGE.EMPTY_CATEGORY,
  EMPTY_LOCATION: WORDS_MESSAGE.EMPTY_LOCATION,
  EMPTY_SUPPLIER: WORDS_MESSAGE.EMPTY_SUPPLIER,
  EMPTY_STAFF: WORDS_MESSAGE.EMPTY_STAFF,
  EMPTY_PROJECT_USER: WORDS_MESSAGE.EMPTY_PROJECT_USER,
  EMPTY_CLIENT: WORDS_MESSAGE.EMPTY_CLIENT,
  EMPTY_SKILL: WORDS_MESSAGE.EMPTY_SKILL,
  EMPTY_DAILY_WORK_RECORD: WORDS_MESSAGE.EMPTY_DAILY_WORK_RECORD,
  EMPTY_PROGRESS_RECORD: WORDS_MESSAGE.EMPTY_PROGRESS_RECORD,
  DELETE_CONFIRM: WORDS_MESSAGE.DELETE_CONFIRM,
  RESTRICTED_EDIT: WORDS_MESSAGE.RESTRICTED_EDIT,
  PAGE_UNDER_CONSTRUCTION: WORDS_MESSAGE.PAGE_UNDER_CONSTRUCTION,
  LOGOUT_CONFIRM_PROJECT: WORDS_MESSAGE.LOGOUT_CONFIRM_PROJECT,
  LOGOUT_CONFIRM_INVENTORY: WORDS_MESSAGE.LOGOUT_CONFIRM_INVENTORY,
  SUCCESS_TITLE: WORDS_MESSAGE.SUCCESS_TITLE,
  ERROR_TITLE: WORDS_MESSAGE.ERROR_TITLE,
  EMPTY_DATA: WORDS_MESSAGE.EMPTY_DATA,
  NO_OPTIONS: WORDS_MESSAGE.NO_OPTIONS,
  FEATURE_NOT_IMPLEMENTED: WORDS_MESSAGE.FEATURE_NOT_IMPLEMENTED,
  STAFF_SHORTAGE: WORDS_MESSAGE.STAFF_SHORTAGE,
  STAFF_SURPLUS: WORDS_MESSAGE.STAFF_SURPLUS,
  STAFF_OPTIMAL: WORDS_MESSAGE.STAFF_OPTIMAL,
  DUMMY_LOGIC_NOTICE: WORDS_MESSAGE.DUMMY_LOGIC_NOTICE,
  FETCH_ERROR: WORDS_MESSAGE.FETCH_ERROR,
  LOADING: WORDS_MESSAGE.LOADING,
};

export const PLACEHOLDERS = {
  EMAIL: WORDS_PERSON.EMAIL_PLACEHOLDER,
  PASSWORD: WORDS_PERSON.PASSWORD_PLACEHOLDER,
  SELECT: WORDS_UI.SELECT,
};
