/**
 * 第一階層：抽象定義（Global / Primitive Tokens）
 */

// システム・モジュール名に関する定数群
export const WORDS_SYSTEM = {
  SYSTEM_ID: 'p2608',
  SYSTEM_NAME: '工賃管理システム',

  // モジュール名
  AGGREGATION: '集計系',
  RECORDING: '記録系',
  SETTINGS: '設定系',
  REPORT: '参照有・入力無',
  TRANSACTION_KANA: '参照有・入力有',
  SUB_MASTER: '参照無・入力有',
  SCREEN_COMPOSITION: 'サイドバーメニュー',
  UNDER_CONSIDERATION: '検討中',

  // メニュー・画面名
  STAFF_SETTING: '職員設定',
  PROJECT_INFO: '案件情報',
  PROJECT_USER: '利用者設定',
  CLIENT_SETTING: '取引先設定',
  SKILL_SETTING: 'スキル設定',
  BASE_WAGE_SETTING: '工賃単価設定',
  DAILY_WORK_RECORD: '作業記録',
  PROGRESS_RECORD: '進捗記録',
  FINANCIAL_RECORD: '収支一覧',
  MATERIAL_EXPENSE_RECORD: '材料費・経費記録',
  ASSIGNEE_SUMMARY: '担当状況集計',
  BUDGET_PLANNING: '予算編成',
  ASSIGNEE_ALLOCATION: '担当者割当',
  SKILL_LEVEL_SETTING: 'スキルレベル設定',
  SKILL_EVALUATION: 'スキル評価',
  BASE_WAGE_ASSIGNMENT: '工賃単価評価',
  PROGRESS_STATUS: '進捗状況',
  REWARD_ALLOCATION: '月次精算',
  FINANCIAL_SUMMARY: '就労支援事業活動収支（時期別）',
  WELFARE_FINANCIAL_SUMMARY: '福祉事業活動収支',
  WAGE_SUMMARY: '工賃・控除明細',
  SYSTEM_COMPOSITION: 'システム構成',
  SCREEN_DAILY_WORK: '作業記録',
  SCREEN_PROJECT: '案件',
  SCREEN_USER: '利用者',
  SCREEN_STAFF: '職員',
  SCREEN_CLIENT: '取引先',
  SCREEN_DASHBOARD: 'ダッシュボード',
  SCREEN_FINANCE: '収支',
  SCREEN_SKILL: 'スキル体系',
  SCREEN_WAGE: '工賃体系',
  TAB_SCREEN_COMPOSITION: '画面構成',
  TAB_TABLE_COMPOSITION: 'テーブル構成',
  TAB_MAIN_FEATURES: '主要機能',
  TAB_WORKFLOW: 'ワークフロー',
};

// 汎用・共通の定数群
export const WORDS_COMMON = {
  TYPE: '区分',
  RESTRICTION: '制限',
  CANCELED: '中止',
  DESCRIPTION: '説明',
  NAME: '名称',
  ADD: '追加',
  EDIT: '編集',
  DELETE: '削除',
  SAVE: '保存',
  CANCEL: '取消',
  CLOSE: '閉じる',
  YOMIGANA: 'よみがな',
  UNIT: '単位',
  YES: 'はい',
  YES_VALUE: 'yes',
  NO: 'いいえ',
  NO_VALUE: 'no',
};

// 人に関する定数群
export const WORDS_PERSON = {
  NAME: '氏名',
  ROLE: 'ロール',
  PERSON_IN_CHARGE: '記録者',
  ASSIGNEE: '担当者',
  ASSIGNEE_TYPE: '担当者区分',
  ROLE_ADMIN: 'システム管理者',
  ROLE_STAFF: '職員',
  ROLE_MEMBER: '利用者',
};

// 連絡先・認証に関する定数群
export const WORDS_CONTACT_AUTH = {
  EMAIL: 'メールアドレス',
  EMAIL_PLACEHOLDER: 'user@example.com',
  PASSWORD: 'パスワード',
  PASSWORD_PLACEHOLDER: '••••••••',
  PHONE: '電話番号',
  LOGIN: 'ログイン',
  LOGOUT: 'ログアウト',
};

// 組織・場所に関する定数群
export const WORDS_ORG_LOCATION = {
  CLIENT: '取引先',
  CUSTOMER: '顧客',
  OUTSOURCE: '外注先',
  CLIENT_INTERNAL_BUSINESS: '無し（自主事業）',
};

// 時間・記録に関する定数群
export const WORDS_TIME = {
  START_DATE: '開始日',
  END_DATE: '終了日',
  WORK_TIME: '作業時間 (h)',
  CURRENT_MONTH_WORK_TIME: '今月作業時間 (h)',
  CUMULATIVE_WORK_TIME: '累積作業時間 (h)',
};

// 案件・作業に関する定数群
export const WORDS_PROJECT = {
  PROJECT: '案件',
  PROJECT_TYPE: '精算時期',
  PROJECT_TYPE_ONE_OFF: '案件終了時',
  PROJECT_TYPE_ONE_OFF_VALUE: 'one-off',
  PROJECT_TYPE_ONGOING: '毎月',
  PROJECT_TYPE_ONGOING_VALUE: 'ongoing',
  PROJECT_TYPE_OTHER: 'その他',
  PROJECT_TYPE_OTHER_VALUE: 'その他',
  TASK: 'タスク',
  SKILL: 'スキル',
  REQUIRED_SKILLS: 'スキル',
  INCENTIVE_BUDGET: 'インセンティブ予算額',
  CONTRIBUTION_RATIO: '報酬配分比',
  PROGRESS_RATE: '進捗率',
  STATUS_NOT_STARTED: '未着手',
  STATUS_IN_PROGRESS: '進行中',
  STATUS_FINISHED: '終了',
  STATUS_CANCELED: '中止',
  PREV_MONTH_PROGRESS: '月初進捗率 (%)',
  CURRENT_MONTH_PROGRESS: '月末進捗率 (%)',
  REVENUE: '収益',
  EXPENSE: '費用',
  RESERVE: '積立金',
  SURPLUS: '余剰',
  FINANCIAL_TYPE: '収支区分',
  SUBJECT: '科目',
  AMOUNT: '金額',
  TOTAL: '合計',
  SUBJECT_REVENUE_SALES: '就労支援事業収益',
  SUBJECT_EXPENSE_LABOR_MEMBER: '労務費（利用者工賃）',
  SUBJECT_DEDUCTION: '控除',
  SUBJECT_EXPENSE_LABOR_OTHER: '労務費（利用者工賃以外）',
  SUBJECT_EXPENSE_OUTSOURCE: '外注加工費',
  SUBJECT_EXPENSE_MATERIAL: '材料費',
  SUBJECT_EXPENSE_OTHER: '経費',
  BASE_WAGE: '工賃単価',
  SUBJECT_RESERVE_WAGE: '工賃変動積立金',
  SUBJECT_RESERVE_EQUIPMENT: '設備等修繕維持積立金',
  SUBJECT_SURPLUS: '余剰',
  SKILL_LEVEL: 'スキルレベル',
  REWARD_ALLOCATION_AMOUNT: '報酬配分額',
  DEDUCTION_AMOUNT: '差引額',
  REWARD_UNIT_PRICE: '報酬単価',
  PROJECT_STATUS: '案件進捗',
  TASK_STATUS: 'タスク進捗',
  ASSIGNEE_TYPE_INTERNAL: '内製',
  ASSIGNEE_TYPE_INTERNAL_VALUE: 'internal',
  ASSIGNEE_TYPE_EXTERNAL: '外注',
  ASSIGNEE_TYPE_EXTERNAL_VALUE: 'external',
  FINANCIAL_PERIOD: '対象時期',
  RECORDED_DATE: '記録日',
};

// メッセージに関する定数群
export const WORDS_MESSAGE = {
  SAVE_SUCCESS: '保存が完了しました。',
  SAVE_ERROR: '保存中にエラーが発生しました。コンソールをご確認ください。',
  EMPTY_STAFF: '職員データがありません',
  EMPTY_PROJECT_USER: '利用者データがありません',
  EMPTY_CLIENT: '取引先データがありません',
  EMPTY_SKILL: 'スキルデータがありません',
  EMPTY_BASE_WAGE: '工賃単価データがありません',
  EMPTY_BASE_WAGE_ASSIGNMENT: '工賃単価割当データがありません',
  EMPTY_FINANCIAL_RECORD: '収支記録がありません',
  EMPTY_DAILY_WORK_RECORD: '作業記録がありません',
  EMPTY_PROGRESS_RECORD: '進捗記録がありません',
  EMPTY_BUDGET: '予算データがありません',
  RESTRICTED_EDIT: '最新棚卸以前のデータは編集不可です',
  PAGE_UNDER_CONSTRUCTION: '選択されたページは現在開発中です。',
  FEATURE_NOT_IMPLEMENTED: '編集機能は未実装です',
  FETCH_ERROR: 'データの取得に失敗しました',
  LOADING: 'Loading...',
  SELECT: '選択してください',
};

/**
 * 第二階層：具象定義（Semantic / Component Tokens）
 */

export const SYSTEM_NAME = WORDS_SYSTEM.SYSTEM_NAME;
export const SYSTEM_ID = WORDS_SYSTEM.SYSTEM_ID;

export const MENU_CATEGORIES = {
  AGGREGATION: WORDS_SYSTEM.AGGREGATION,
  RECORDING: WORDS_SYSTEM.RECORDING,
  SETTINGS: WORDS_SYSTEM.SETTINGS,
  SCREEN_COMPOSITION: WORDS_SYSTEM.SCREEN_COMPOSITION,
};

export const MENU_SUBCATEGORIES = {
  AGGREGATION: WORDS_SYSTEM.REPORT,
  RECORDING: WORDS_SYSTEM.TRANSACTION_KANA,
  SETTINGS: WORDS_SYSTEM.SUB_MASTER,
  SCREEN_COMPOSITION: WORDS_SYSTEM.UNDER_CONSIDERATION,
};

export const PAGE_NAMES = {
  STAFF: WORDS_SYSTEM.STAFF_SETTING,
  PROJECT_INFO: WORDS_SYSTEM.PROJECT_INFO,
  PROJECT_USER: WORDS_SYSTEM.PROJECT_USER,
  CLIENT: WORDS_SYSTEM.CLIENT_SETTING,
  SKILL: WORDS_SYSTEM.SKILL_SETTING,
  SKILL_LEVEL: WORDS_SYSTEM.SKILL_LEVEL_SETTING,
  SKILL_EVALUATION: WORDS_SYSTEM.SKILL_EVALUATION,
  BASE_WAGE: WORDS_SYSTEM.BASE_WAGE_SETTING,
  BASE_WAGE_ASSIGNMENT: WORDS_SYSTEM.BASE_WAGE_ASSIGNMENT,
  DAILY_WORK_RECORD: WORDS_SYSTEM.DAILY_WORK_RECORD,
  PROGRESS_RECORD: WORDS_SYSTEM.PROGRESS_STATUS,
  PROJECT_FINANCIAL_RECORD: WORDS_SYSTEM.MATERIAL_EXPENSE_RECORD,
  FINANCIAL_RECORD: WORDS_SYSTEM.FINANCIAL_RECORD,
  REWARD_ALLOCATION: WORDS_SYSTEM.REWARD_ALLOCATION,
  ASSIGNEE_SUMMARY: WORDS_SYSTEM.ASSIGNEE_SUMMARY,
  BUDGET_PLANNING: WORDS_SYSTEM.BUDGET_PLANNING,
  ASSIGNEE_ALLOCATION: WORDS_SYSTEM.ASSIGNEE_ALLOCATION,
  FINANCIAL_SUMMARY: WORDS_SYSTEM.FINANCIAL_SUMMARY,
  WELFARE_FINANCIAL_SUMMARY: WORDS_SYSTEM.WELFARE_FINANCIAL_SUMMARY,
  WAGE_SUMMARY: WORDS_SYSTEM.WAGE_SUMMARY,
  SCREEN_COMPOSITION: WORDS_SYSTEM.SYSTEM_COMPOSITION,
  SCREEN_DAILY_WORK: WORDS_SYSTEM.SCREEN_DAILY_WORK,
  SCREEN_PROJECT: WORDS_SYSTEM.SCREEN_PROJECT,
  SCREEN_USER: WORDS_SYSTEM.SCREEN_USER,
  SCREEN_STAFF: WORDS_SYSTEM.SCREEN_STAFF,
  SCREEN_CLIENT: WORDS_SYSTEM.SCREEN_CLIENT,
  SCREEN_DASHBOARD: WORDS_SYSTEM.SCREEN_DASHBOARD,
  SCREEN_FINANCE: WORDS_SYSTEM.SCREEN_FINANCE,
  SCREEN_SKILL: WORDS_SYSTEM.SCREEN_SKILL,
  SCREEN_WAGE: WORDS_SYSTEM.SCREEN_WAGE,
  TAB_SCREEN_COMPOSITION: WORDS_SYSTEM.TAB_SCREEN_COMPOSITION,
  TAB_TABLE_COMPOSITION: WORDS_SYSTEM.TAB_TABLE_COMPOSITION,
  TAB_MAIN_FEATURES: WORDS_SYSTEM.TAB_MAIN_FEATURES,
  TAB_WORKFLOW: WORDS_SYSTEM.TAB_WORKFLOW,
};

export const TABLE_COLUMNS = {
  // 共通
  YOMIGANA: WORDS_COMMON.YOMIGANA,
  DESCRIPTION: WORDS_COMMON.DESCRIPTION,
  NAME: WORDS_PERSON.NAME,
  PERSON_IN_CHARGE: WORDS_PERSON.PERSON_IN_CHARGE,

  // 取引先
  CLIENT_NAME: WORDS_ORG_LOCATION.CLIENT, // 統合

  // アカウント
  ROLE: WORDS_PERSON.ROLE,
  EMAIL: WORDS_CONTACT_AUTH.EMAIL,
  PASSWORD: WORDS_CONTACT_AUTH.PASSWORD,
  CONTACT_PERSON: WORDS_PERSON.ASSIGNEE, // 担当者に統合
  PHONE: WORDS_CONTACT_AUTH.PHONE,

  // 記録
  TYPE: WORDS_COMMON.TYPE,
  RESTRICTION: WORDS_COMMON.RESTRICTION,

  // 案件情報
  PROJECT_ID: '案件ID',
  TASK_ID: 'タスクID',
  PROJECT_NAME: WORDS_PROJECT.PROJECT, // 案件に統合
  PROJECT_TYPE: WORDS_PROJECT.PROJECT_TYPE,
  START_DATE: WORDS_TIME.START_DATE,
  END_DATE: WORDS_TIME.END_DATE,
  CUSTOMER: WORDS_ORG_LOCATION.CUSTOMER,
  TASK: WORDS_PROJECT.TASK,
  REQUIRED_SKILLS: WORDS_PROJECT.REQUIRED_SKILLS,
  INCENTIVE_BUDGET: WORDS_PROJECT.INCENTIVE_BUDGET,
  ASSIGNEE: WORDS_PERSON.ASSIGNEE,
  SKILL_NAME: WORDS_PROJECT.SKILL, // スキルに統合
  SKILL_LEVEL: WORDS_PROJECT.SKILL_LEVEL,
  BASE_WAGE: WORDS_PROJECT.BASE_WAGE,

  // 作業記録
  USER_NAME: WORDS_PERSON.ASSIGNEE, // 担当者に統合
  WORK_TIME: WORDS_TIME.WORK_TIME,
  NOTES: WORDS_COMMON.DESCRIPTION,

  // 進捗記録
  PREV_MONTH_PROGRESS: WORDS_PROJECT.PREV_MONTH_PROGRESS,
  CURRENT_MONTH_PROGRESS: WORDS_PROJECT.CURRENT_MONTH_PROGRESS,
  CURRENT_MONTH_WORK_TIME: WORDS_TIME.CURRENT_MONTH_WORK_TIME,
  CUMULATIVE_WORK_TIME: WORDS_TIME.CUMULATIVE_WORK_TIME,
  CONTRIBUTION_RATIO: WORDS_PROJECT.CONTRIBUTION_RATIO,
  REWARD_ALLOCATION_AMOUNT: WORDS_PROJECT.REWARD_ALLOCATION_AMOUNT,
  DEDUCTION_AMOUNT: WORDS_PROJECT.DEDUCTION_AMOUNT,
  REWARD_UNIT_PRICE: WORDS_PROJECT.REWARD_UNIT_PRICE,
  PROGRESS_RATE: WORDS_PROJECT.PROGRESS_RATE,
  PROJECT_STATUS: WORDS_PROJECT.PROJECT_STATUS,
  TASK_STATUS: WORDS_PROJECT.TASK_STATUS,
  IS_CANCELED: WORDS_COMMON.CANCELED,
  ASSIGNEE_TYPE: WORDS_PERSON.ASSIGNEE_TYPE,

  // 予算・収支
  FINANCIAL_TYPE: WORDS_PROJECT.FINANCIAL_TYPE,
  REVENUE: '収益　A',
  EXPENSE: '費用　B',
  RESERVE: '積立金　C',
  SURPLUS: '余剰　A-（B+C）',
  SUBJECT: WORDS_PROJECT.SUBJECT,
  AMOUNT: WORDS_PROJECT.AMOUNT,
  REMARKS: '備考',
  TOTAL: WORDS_PROJECT.TOTAL,
  PERIOD: WORDS_PROJECT.FINANCIAL_PERIOD,
  RECORDED_DATE: WORDS_PROJECT.RECORDED_DATE,
  SUBJECT_REVENUE_SALES: WORDS_PROJECT.SUBJECT_REVENUE_SALES,
  SUBJECT_EXPENSE_LABOR_MEMBER: WORDS_PROJECT.SUBJECT_EXPENSE_LABOR_MEMBER,
  SUBJECT_DEDUCTION: WORDS_PROJECT.SUBJECT_DEDUCTION,
  SUBJECT_EXPENSE_LABOR_OTHER: WORDS_PROJECT.SUBJECT_EXPENSE_LABOR_OTHER,
  SUBJECT_EXPENSE_OUTSOURCE: WORDS_PROJECT.SUBJECT_EXPENSE_OUTSOURCE,
  SUBJECT_EXPENSE_MATERIAL: WORDS_PROJECT.SUBJECT_EXPENSE_MATERIAL,
  SUBJECT_EXPENSE_OTHER: WORDS_PROJECT.SUBJECT_EXPENSE_OTHER,
  SUBJECT_RESERVE_WAGE: WORDS_PROJECT.SUBJECT_RESERVE_WAGE,
  SUBJECT_RESERVE_EQUIPMENT: WORDS_PROJECT.SUBJECT_RESERVE_EQUIPMENT,
};

export const LOGIN_LABELS = {
  EMAIL: WORDS_CONTACT_AUTH.EMAIL,
  PASSWORD: WORDS_CONTACT_AUTH.PASSWORD,
};

export const BUTTON_LABELS = {
  LOGIN: WORDS_CONTACT_AUTH.LOGIN,
  LOGOUT: WORDS_CONTACT_AUTH.LOGOUT,
  ADD: WORDS_COMMON.ADD,
  SAVE: WORDS_COMMON.SAVE,
  CANCEL: WORDS_COMMON.CANCEL,
  DELETE: WORDS_COMMON.DELETE,
};

export const MESSAGES = {
  SAVE_SUCCESS: WORDS_MESSAGE.SAVE_SUCCESS,
  SAVE_ERROR: WORDS_MESSAGE.SAVE_ERROR,
  EMPTY_STAFF: WORDS_MESSAGE.EMPTY_STAFF,
  EMPTY_PROJECT_USER: WORDS_MESSAGE.EMPTY_PROJECT_USER,
  EMPTY_CLIENT: WORDS_MESSAGE.EMPTY_CLIENT,
  EMPTY_SKILL: WORDS_MESSAGE.EMPTY_SKILL,
  EMPTY_BASE_WAGE: WORDS_MESSAGE.EMPTY_BASE_WAGE,
  EMPTY_BASE_WAGE_ASSIGNMENT: WORDS_MESSAGE.EMPTY_BASE_WAGE_ASSIGNMENT,
  EMPTY_FINANCIAL_RECORD: WORDS_MESSAGE.EMPTY_FINANCIAL_RECORD,
  EMPTY_DAILY_WORK_RECORD: WORDS_MESSAGE.EMPTY_DAILY_WORK_RECORD,
  EMPTY_PROGRESS_RECORD: WORDS_MESSAGE.EMPTY_PROGRESS_RECORD,
  EMPTY_BUDGET: WORDS_MESSAGE.EMPTY_BUDGET,
  RESTRICTED_EDIT: WORDS_MESSAGE.RESTRICTED_EDIT,
  PAGE_UNDER_CONSTRUCTION: WORDS_MESSAGE.PAGE_UNDER_CONSTRUCTION,
  FEATURE_NOT_IMPLEMENTED: WORDS_MESSAGE.FEATURE_NOT_IMPLEMENTED,
  FETCH_ERROR: WORDS_MESSAGE.FETCH_ERROR,
  LOADING: WORDS_MESSAGE.LOADING,
};

export const PLACEHOLDERS = {
  EMAIL: WORDS_CONTACT_AUTH.EMAIL_PLACEHOLDER,
  PASSWORD: WORDS_CONTACT_AUTH.PASSWORD_PLACEHOLDER,
  SELECT: WORDS_MESSAGE.SELECT,
};



export const OPTIONS = {
  PROJECT_TYPE_OPTIONS: [
    { label: WORDS_PROJECT.PROJECT_TYPE_ONGOING, value: WORDS_PROJECT.PROJECT_TYPE_ONGOING_VALUE },
    { label: WORDS_PROJECT.PROJECT_TYPE_ONE_OFF, value: WORDS_PROJECT.PROJECT_TYPE_ONE_OFF_VALUE }
  ],
  YES_NO: [
    { label: WORDS_COMMON.YES, value: WORDS_COMMON.YES_VALUE },
    { label: WORDS_COMMON.NO, value: WORDS_COMMON.NO_VALUE }
  ],
  ASSIGNEE_TYPE_OPTIONS: [
    { label: WORDS_PROJECT.ASSIGNEE_TYPE_INTERNAL, value: WORDS_PROJECT.ASSIGNEE_TYPE_INTERNAL_VALUE },
    { label: WORDS_PROJECT.ASSIGNEE_TYPE_EXTERNAL, value: WORDS_PROJECT.ASSIGNEE_TYPE_EXTERNAL_VALUE }
  ]
};

export const STAFF_ROLE_OPTIONS = [
  { label: WORDS_PERSON.ROLE_ADMIN, value: WORDS_PERSON.ROLE_ADMIN },
  { label: WORDS_PERSON.ROLE_STAFF, value: WORDS_PERSON.ROLE_STAFF }
];

export const MEMBER_ROLE_OPTIONS = [
  { label: WORDS_PERSON.ROLE_MEMBER, value: WORDS_PERSON.ROLE_MEMBER }
];
